jwt:
  secret: "mySuperSecretKeyWithAtLeast32Characters123!"
  expiration: 86400000  # 24h en ms

spring:
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

server:
  port: 8081